		SUBROUTINE MATSCA(A,IROW,ICOL,B,C)
		IMPLICIT REAL*8 (A-H)
		IMPLICIT REAL*8 (O-Z)
		REAL*8 A(IROW,ICOL),C(IROW,ICOL)
		DO 110 I=1,IROW
		DO 110 J=1,ICOL
		C(I,J)=B*A(I,J)
110 	CONTINUE
		RETURN
		END