		SUBROUTINE MATMUL(A,IROW,ICOL,B,JROW,JCOL,C)
		IMPLICIT REAL*8 (A-H)
		IMPLICIT REAL*8 (O-Z)
		REAL*8 A(IROW,ICOL),B(JROW,JCOL),C(IROW,JCOL)
		DO 110 I=1,IROW
		DO 110 J=1,JCOL
		C(I,J)=0.
		DO 110 K=1,ICOL
		C(I,J)= C(I,J)+A(I,K)*B(K,J)
110 	CONTINUE
		RETURN
		END