		!C THE FIRST THREE STATEMENTS INVOKE THE ABSOFT RANDOM NUMBER GENERATOR ON THE MACINTOSH
		!GLOBAL DEFINE
			!INCLUDE 'quickdraw.inc'
		!END
		IMPLICIT REAL*8 (A-H)
		IMPLICIT REAL*8 (O-Z)
		SIGNOISE=1.
		OPEN(1,STATUS='UNKNOWN',FILE='DATFIL')
		DO 10 I=1,1000
			CALL GAUSS(X,SIGNOISE)
			WRITE(9,*)I,X
			WRITE(1,*)I,X
10 	CONTINUE
		CLOSE(1)
		!PAUSE
		END
		SUBROUTINE GAUSS(X,SIG)
			IMPLICIT REAL*8(A-H)
			IMPLICIT REAL*8(O-Z)
			real :: a = 0.0
			REAL SUM
			SUM=0
			call random_seed()
			DO 14 J=1,6
				!C THE NEXT STATEMENT PRODUCES A UNIF. DISTRIBUTED NUMBER FROM -32768 TO +32768
				
				call random_number(a)
				!IRAN=Random()
				SUM=SUM+a*65536.0-32768
14 		CONTINUE
			X=SUM/65536
			X=1.414*X*SIG
			RETURN
		END